apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:V0979js3T7y47ASTzT5HRG1tcCiC2YTnXeovVgyBNIDb4kiyKw==,iv:dbHtQz86h2ZfdNcNHl2h4HILAfoYGcgiQI0jrgkf90s=,tag:xveEI4seGnFm1qAGUHZDuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yydafte6rdelccuugmt6qvlp69sxmavpef4kf24akr6fwhap7ctqpmg2n2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUFo5c21POGx4NGJDc2tW
            em1lNGRObGxyNEdCV1MwOHBsV0JoeWpDMUJRCjd3SngxVWtVckwyNU0yZDdyTHhX
            YWl4UEk4aVVTbHQ4WkRha1Y3SW5TVUkKLS0tIGJaT2N1NHBJbEVIa1hkZEhZNnda
            dGo2MHpreWI1QXNLb04ySXZmcUFDU0UKnha7iwazvCbWgUK4gdKFnpcgaXtJWLR8
            S+4JloCXwYEE6WZVUbx/ZJGoNfVu96IjqTAN+G/CcrGkgmfidsBsuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-05T13:35:28Z"
    mac: ENC[AES256_GCM,data:OtcM1+O+CHvoo0vVDirO0VeXna9KCEfY5ikEydcFDQX2+5AbIEBaOfhiYt7M8uDicq1Jdn/SWGtbA2BNgnJ3LcTNyFNXT3NuLHCA7zRHfcZPeqklJkzOCUj5cljgqiCNgUOQQ7aj5wkMMw6NPA+6OG2qoNGAQRfvHzN+Q3nDEwM=,iv:9GjNSWM3NaAW4lZ6LqNM/3exhgcB61qqj6KWmKVpu2s=,tag:j/W8TLpd2cEVjnTWIg9SBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
