---
# Name of the tunnel you want to run
tunnel: dev-cluster
credentials-file: /etc/cloudflared/creds/credentials.json
# Serves the metrics server under /metrics and the readiness server under /ready
metrics: 0.0.0.0:2000
no-autoupdate: true
originRequest:
  http2Origin: true

ingress:
  ### Proxy nginx to the k8s ingress (ingress-nginx) to hand off to Services
  # internet --> cloudflared tunnel --> local DNS --> ingress --> service
  - hostname: "${SECRET_DOMAIN}"
    service: http://ingress-nginx-controller.networking
  - hostname: "*.${SECRET_DOMAIN}"
    service: http://ingress-nginx-controller.networking

  ### Proxy traffic to the Kubernetes Services directly
  # - hostname: "echo.${SECRET_EXT_DOMAIN}"
  #   service: http://echo-server.default:8080

  ### "Else" rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
  - service: http_status:404
