apiVersion: v1
metadata:
    name: cloudflared-credentials
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
kind: Secret
data:
    credentials.json: ENC[AES256_GCM,data:4a0Jiqtjk59pTcQ9ET4wKVEOF7uL4lIRf1ZOPLaEF4wbcVnYO24fiYiL8uP1o22FDHEJy9WD6qeusIE/b6r+r+fBLKfHub0uTqgCS44Mkc4mTFIY7fAVedNBTVqxbLlZJ9/IyYkEPjZCzRM04BmqPVsu65PaYOedShsl4ZENil7rNuB0FUrAkOdJYZCM3n4N0TTQrditgqWp4J9crEsGPj/iOEB14pLQzT2KRe7qm+EN+28JIk3jGSfmS104cQdabTfyhrRGWjXgU5Lxy89GFKHfxuJ4YDpl,iv:Tx6yUJ2ilqhgQe3fojgGR/tNXuIq2BWbJJk0zxLqSZo=,tag:n9AzztoOIh0WVIsEik5afw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yydafte6rdelccuugmt6qvlp69sxmavpef4kf24akr6fwhap7ctqpmg2n2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWNpSkxGa21NeDlxSDk3
            NndNM3o4Wk8rdGNLUnJjSjlZZU1Zbm9tTlRzClVjMnVUUEpnQjdWQ05hUVhMT2ln
            ajZDcWE0cGVCNjhXbGhiVHZ6d0svU3MKLS0tIEFyMk9EN3hsVlg1Z3NxQVNqdSt5
            WkRueGdDYlJMY01tK1ljM1piNUkrblEK6ArfC60dea1bVH4yKTsTBT172nu8GTlC
            th4dfxqNxFcesSmoDYDmsGnKW+IOzBo+uBZdwIQRPAyoCXjlTGBd+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-05T18:14:37Z"
    mac: ENC[AES256_GCM,data:I+kSQcdJVXMQZGFzfzbiXvcYVy2Rh67p/mj3zfQS2JGOKGqVAQmGgv9l6ddejwKr9M3ZRmeAt6y9tD1K0OvOoygjRFQifteolCPzOHPOTaDv9o8k3G7X0L1iGhGXdfk04BfBFgDOsrny+S7lRl7Qx5cEwV7reEFAZ33YYL8kP24=,iv:jl1L9o7Wjf39W0+yRjAKar0k0EYaYS798DX7CptqE/A=,tag:v+8bbVCCqS2NFKQ8sQjJQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
